### ISSUE TITLE
TEst

### ISSUE THREAD

**Issue by smashstack-chester** [smashstack-chester/smash-optimized#1]
tsete

**Comment by smashstack-chester** [comment]
**What is handling time?**\nEvery time you list

**Comment by smashstack-chester** [comment]
| If payment clears by: | Your package must be scanned by: | |:-------------:|:-------------:|| Monday, 9 am PT | Wednesday, 11:59:59 pm PT |

**Comment by smashstack-chester** [comment]
| If payment clears by: | Your package must be scanned by: |\n|:-------------:|:-------------:|
| Monday, 9 am PT | Wednesday, 11:59:59 pm PT |

**Comment by smashstack-randi** [comment]
| If payment clears by: | Your package must be scanned by: |
|:-------------:|:-------------:|
| Monday, 9 am PT | Wednesday, 11:59:59 pm PT |

**Comment by smashstack-chester** [comment]
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

**Comment by smashstack-chester** [comment]
| Tables        | Are           | Cool  || ------------- |:-------------:| -----:|| col 3 is      | right-aligned | $1600 || col 2 is      | centered      |   $12 || zebra stripes | are neat      |    $1 |

**Comment by smashstack-chester** [comment]
| Tables        | Are           | Cool  |\n| ------------- |:-------------:| -----:|\n| col 3 is      | right-aligned | $1600 |\n| col 2 is      | centered      |   $12 |\n| zebra stripes | are neat      |    $1 |

**Comment by smashstack-randi** [comment]
- list item 1
- list item 2
- list item 3

**Comment by smashstack-chester** [comment]
[link text](http://someurl)

**Comment by smashstack-chester** [comment]
![image](http://pics.ebaystatic.com/aw/pics/sc/build-your-business/deliver-great-service/handling/HandlingTime_web_376x290.gif)

**Comment by smashstack-chester** [comment]
|If payment clears by:|	Your package must be scanned by:
|---------------------|:--------------------------------|
|Monday, 9 am PT|	Wednesday, 11:59:59 pm PT|
|Thursday, 3 pm PT|	Monday, 11:59:59 pm PT|
|Friday, 3 pm PT|	Tuesday, 11:59:59 pm PT|
**Examples of one-day handling time**
|If payment clears by:|	Your package must be scanned by:
|---------------------|:--------------------------------|
|Monday, 9 am PT|	Tuesday, 11:59:59 pm PT|
|Monday, 3 pm PT|	Tuesday, 11:59:59 pm PT|
|Friday 3 pm PT|	Monday 11:59:59 pm PT|
**Examples of same-day handling time (assumes an order cut-off of 2 pm PT)**
|If payment clears by:|	Your package must be scanned by:|
|---------------------|:--------------------------------|
|Monday, 9 am PT|	Monday, 11:59:59 pm PT|
|Monday, 3 pm PT|	Tuesday, 11:59:59 pm PT|
|Friday 3 pm PT|	Monday 11:59:59 pm PT|

**Comment by smashstack-chester** [comment]
**Examples of one-day handling time**
|If payment clears by:|	Your package must be scanned by:
|---------------------|:--------------------------------|
|Monday, 9 am PT|	Tuesday, 11:59:59 pm PT|
|Monday, 3 pm PT|	Tuesday, 11:59:59 pm PT|
|Friday 3 pm PT|	Monday 11:59:59 pm PT|

**Comment by smashstack-chester** [comment]
| If payment clears by:        | Your package must be scanned by:|\n
| ------------- |:-------------:|\n
| Monday, 9 am PT      | Wednesday, 11:59:59 pm PT |\n
| Thursday, 3 pm PT      | Monday, 11:59:59 pm PT |\n
| Friday, 3 pm PT | Tuesday, 11:59:59 pm PT |\n

**Comment by smashstack-chester** [comment]
| If payment clears by:        | Your package must be scanned by:|
| ------------- |:-------------:|
| Monday, 9 am PT      | Wednesday, 11:59:59 pm PT |
| Thursday, 3 pm PT      | Monday, 11:59:59 pm PT |
| Friday, 3 pm PT | Tuesday, 11:59:59 pm PT |

**Comment by smashstack-chester** [comment]
|         | Average Ad Rate           | Max Ad Rate  |
    | ------------- |-------------| -----|
    | col 3 is      | right-aligned | $1600 |
    | col 2 is      | centered      |   $12 |
    | zebra stripes | are neat      |    $1 |
